### PR TITLE
Trying to fix an error about the shells

### PR DESCRIPTION
**Pull request by Akrai**
Trying to fix an error from @azurata in the aur package

### CODE REVIEW

**Comment by a-m-s** [comment]
I'm not using this any more, and this repo was only a fork in the first place. Would you like to take ownership?

**Comment by Akrai** [comment]
as you want, i don't have any problem with it

**Comment by a-m-s** [comment]
I can't transfer ownership of this repo because you already have a fork with this repository name, but you can just change to AUR to point to your fork. I'll delete this one after a month or so.

**Comment by Akrai** [comment]
im deleting the fork now

**Pull request merged**
